##  Named of the workflow.
name: TechTrends - Package with Docker

on:
  push:
    branches: ['main']
  pull_request:
    branches: [ main ]

## List the steps to be executed by the workflow
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./project/techtrends/
          file: ./project/techtrends/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/techtrends:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
